import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { SessionProvider } from "next-auth/react"
import { auth } from "@/auth"

const inter = Inter({ subsets: ["latin"] });
import localFont from 'next/font/local'

// Font files can be colocated inside of `pages`
const myFont = localFont({ src: "../fonts/Nohemi-Bold-BF6438cc577b524.woff" })
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "An advanced Auth model",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  return (
      <SessionProvider session={session}>
          <html lang="en">
          <body className={inter.className}>
          {children}
          <Toaster />
          </body>
          </html>
      </SessionProvider>
  )
}
